[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rudelblinken-sdk.workspace = true
spin.workspace = true
talc.workspace = true


[profile.release]
opt-level = "s"
lto = "fat"
panic = "abort"
codegen-units = 1
